name: Build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier (format)
        run: npm run format

      - name: Run ESLint (lint)
        run: npm run lint

      - name: Build project
        run: npm run build
